name: Run Tests

on:
  pull_request:
    branches: [main]
  push:
    branches-ignore: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd backend-workers
          npm ci

      - name: Run tests
        run: |
          cd backend-workers
          npm test

      - name: Run linter
        run: |
          cd backend-workers
          npm run lint

      - name: Security audit
        run: |
          cd backend-workers
          npm audit --audit-level=high
        continue-on-error: true

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run tests
        run: |
          cd frontend
          npm test

      - name: Run linter
        run: |
          cd frontend
          npm run lint

      - name: Type check
        run: |
          cd frontend
          npm run type-check

      - name: Security audit
        run: |
          cd frontend
          npm audit --audit-level=high
        continue-on-error: true

  build-check:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build backend
        run: |
          cd backend-workers
          npm ci
          npm run build

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build
